application: boxguild
version: 1
runtime: python
api_version: 1

handlers:
- url: /o/.*
  script: admin.py
  login: admin

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: main.py

builtins:
- remote_api: on
  
inbound_services:
- warmup


